/* Types for the generated `leaps.js`.
 *
 * The app itself is ported from upstream and stays plain JavaScript — it is
 * regenerated by `scripts/port-leaps/port-main.mjs` and a hand-written .ts
 * copy would be lost on the next sync. This file is the seam: it describes
 * what the island is allowed to call, so the TSX shell is still type-checked
 * against a real surface rather than `any`.
 */

export interface LeapsOptions {
    /** The Plotly namespace. Defaults to `window.Plotly` when omitted. */
    plotly?: unknown;
    /** Factory for the solver Worker. Defaults to `new Worker('worker.js')`. */
    makeWorker?: () => Worker;
    /** A main-thread fallback engine, used where a Worker cannot be built. */
    solver?: unknown;
    /** The KaTeX namespace. Defaults to `window.katex`. */
    katex?: unknown;
}

/** Boots the workspace inside `root` and returns a disposer. */
export function initLeaps(root: HTMLElement, opts?: LeapsOptions): () => void;

export interface LeapsUnitEntry { k: number; u: string }
export interface LeapsUnitSystem {
    name: string;
    label: string;
    len: LeapsUnitEntry;
    stress: LeapsUnitEntry;
    modulus: LeapsUnitEntry;
    force: LeapsUnitEntry;
    defl: LeapsUnitEntry;
    strain: LeapsUnitEntry;
    kitf: LeapsUnitEntry;
    perlen: LeapsUnitEntry;
}
export const UNITS: Record<'SI' | 'US', LeapsUnitSystem>;

export interface LeapsMaterial {
    id: string; name: string; group: string;
    E: number; range: [number, number]; nu: number;
    color: string; tex: string;
}
export const MATERIALS: LeapsMaterial[];

export interface LeapsTemplate {
    id: string; name: string;
    layers: { mat: string; h: number; E?: number; nu?: number }[];
    slips?: number[];
    gear: string;
    params: Record<string, number>;
    points?: string;
}
export const TEMPLATES: LeapsTemplate[];

export interface LeapsLoadKind { id: string; name: string; short: string; icon: string; blurb: string }
export const LOAD_KINDS: LeapsLoadKind[];

export interface LeapsResultRow {
    g: string; key: string; sym: string; q: string;
    get: (p: unknown) => number;
}
export const RESULT_ROWS: LeapsResultRow[];

export interface LeapsResultGroup { id: string; name: string; icon: string }
export const RESULT_GROUPS: LeapsResultGroup[];

export interface LeapsField {
    id: string; sym: string; name: string; q: string; div: boolean;
    get: (p: unknown) => number;
}
export const FIELDS: LeapsField[];

/* The notation table. One spelling per quantity, three renderings. */
export interface LeapsSymbol { b: string; sub?: string; sup?: string }
export const SYM: Record<string, LeapsSymbol>;
/** Markup, for the DOM and for Plotly, which understands sub and sup. */
export function symHtml(id: string): string;
/** Flat, for an option element and for a CSV column. */
export function symText(id: string): string;
/** The TeX source and plain twin of every equation the app shows. */
export const EQ: Record<string, { tex: string; plain: string }>;

declare const LEAPS_APP: {
    init: typeof initLeaps;
    UNITS: typeof UNITS;
    MATERIALS: typeof MATERIALS;
    TEMPLATES: typeof TEMPLATES;
    LOAD_KINDS: typeof LOAD_KINDS;
    RESULT_ROWS: typeof RESULT_ROWS;
    RESULT_GROUPS: typeof RESULT_GROUPS;
    FIELDS: typeof FIELDS;
    SYM: typeof SYM;
    EQ: typeof EQ;
    symHtml: typeof symHtml;
    symText: typeof symText;
};
export default LEAPS_APP;
