// LEAPS: the island shell.
//
// This component owns nothing but the mount and the how-to panel. The
// workspace DOM is `LEAPS_MARKUP`, generated from the standalone app's own
// index.html, and every control in it is driven imperatively by `initLeaps`,
// which is a plain DOM app and not a React one. Keeping the two apart is
// deliberate and is the same split Cross-Section Studio and Gear3D use:
// React is never asked to re-render a canvas, and the engine stays portable
// and testable.
//
// Injecting the markup rather than rewriting it as JSX is what makes "both
// copies of LEAPS are the same program" checkable: forty element ids, kept
// in one place, generated by `scripts/port-leaps/port-markup.mjs`. React
// hands the subtree over once and never touches it again, so there is no
// reconciliation to lose.
//
// Four things are injected into the app, which is why `leaps.js` needs no
// port-time patching of its own:
//   · Plotly, imported here as a module rather than found on `window`;
//   · a Worker factory, because Vite resolves a worker URL at build time;
//   · where the manual lives, which is next door upstream and off-site here;
//   · the typeface, through the `--lp-font` token in leaps.css.
// KaTeX is the exception: the app reads `window.katex`, which BaseLayout
// already loads on every page of this site and the E-Lab page pulls from
// the same CDN. Until it lands, every equation shows its plain-text twin.
//
// Control help is carried on `title` rather than the site's <Tip> component,
// for the same reason the two Three.js ports do it: the side rails are
// `overflow: auto` scroll containers and would clip an absolutely positioned
// popover.
import { useEffect, useRef, useState } from 'react';
import { initLeaps } from './leaps.js';
import { LEAPS_MARKUP } from './markup';
import '../tools.css';
import './leaps.css';

/* The manual is the standalone E-Lab's own documentation page, and there is
   deliberately no second copy of it in this repository: it is generated from
   the same upstream the app is, and two hand-maintained copies of a fifteen-
   section reference cannot be kept in step any more than two copies of forty
   element ids can. Linked rather than duplicated, so it is always the manual
   for the engine that is running. */
const LEAPS_DOCS_URL = 'https://johann-cardenas.github.io/e-labs/leaps/documentation.html';

export default function LeapsApp() {
  const hostRef = useRef<HTMLDivElement>(null);
  const [failure, setFailure] = useState<string | null>(null);

  useEffect(() => {
    const mount = hostRef.current?.querySelector<HTMLElement>('#lp-root');
    if (!mount) return;
    let dispose: (() => void) | undefined;
    // Plotly is loaded on its own, AFTER the workspace mounts. It is the
    // largest thing on the page by a wide margin, and the section viewport
    // is a plain canvas that owes it nothing, so the structure is drawable
    // while the charting library is still arriving. `opts` is the object the
    // app closes over, so filling `plotly` in later is all it takes: the
    // chart path already retries until it has one, exactly as it does on the
    // standalone page where Plotly comes off a deferred CDN tag.
    const opts: { plotly?: unknown; makeWorker: () => Worker; docsHref: string } = {
      // The engine is a UMD that assigns itself to `self`, so the worker
      // module reads it back off there. `new URL(..., import.meta.url)` is
      // the form Vite rewrites into a hashed asset URL at build time; a bare
      // path would 404 from inside _astro/.
      makeWorker: () =>
        new Worker(new URL('./engine/worker.ts', import.meta.url), { type: 'module' }),
      // The app's own link to the manual, in the Performance pane. Upstream
      // it is the relative `documentation.html` next door, which from
      // /tools/leaps/ on this site is a 404.
      docsHref: LEAPS_DOCS_URL,
    };
    try {
      dispose = initLeaps(mount, opts);
      void import('plotly.js-dist-min').then(({ default: P }) => { opts.plotly = P; });
    } catch (err) {
      // The workspace is an imperative DOM app, so a throw here leaves a
      // shell with no controls in it and nothing in the console to explain
      // why. Log the error object, not just its message: the stack is the
      // only thing that names which panel failed to build.
      console.error('LEAPS failed to start', err);
      setFailure(
        err instanceof Error ? err.message : 'The analysis workspace failed to start in this browser.'
      );
    }
    return () => { if (dispose) dispose(); };
  }, []);

  return (
    <div className="cee-tool lp-shell">

      <div className="lp-shell-help">
        <details className="cee-howto">
          <summary>How to use this tool</summary>
          <div className="cee-howto__body">
            <ol>
              <li><strong>Start:</strong> Choose units and a template. Set layer thicknesses, moduli and interfaces.</li>
              <li><strong>Loads:</strong> Choose a load model. For circular contacts, enter two of force, pressure and area. Press Build after editing gear settings.</li>
              <li><strong>Points:</strong> Add evaluation points in the panel or double-click the section.</li>
              <li><strong>Run:</strong> Resolve input warnings, then review the table, contours and key responses.</li>
              <li><strong>Study:</strong> Sweep a parameter in Design study. Export results, a figure or the project.</li>
            </ol>
            <p>Tension is positive; depth and vertical displacement are positive downward. Slip 0 is bonded, 1 is frictionless. Point and line loads are singular at the loaded surface.</p>
          </div>
        </details>

        {/* The manual, beside the how-to rather than inside it: the panel
            above is how to DRIVE the tool, and the documentation is the
            theory, the numerics, the validation cases and the references.
            It opens in a new tab because the workspace holds a section
            somebody is part way through typing. */}
        <a
          className="cee-btn cee-btn--ghost lp-shell-docs"
          href={LEAPS_DOCS_URL}
          target="_blank"
          rel="noopener noreferrer"
        >
          <svg
            viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"
            fill="none" stroke="currentColor" strokeWidth="1.8"
            strokeLinecap="round" strokeLinejoin="round"
          >
            <path d="M4 4.5A1.5 1.5 0 0 1 5.5 3H19v14H5.5A1.5 1.5 0 0 0 4 18.5z" />
            <path d="M4 18.5A1.5 1.5 0 0 0 5.5 20H19v-3" />
            <path d="M8.5 7.5h6M8.5 11h4" />
          </svg>
          Documentation
        </a>
      </div>

      {failure && (
        <p className="cee-warn" role="alert">{failure}</p>
      )}

      <div ref={hostRef} dangerouslySetInnerHTML={{ __html: LEAPS_MARKUP }} />
    </div>
  );
}
