/* American-English spelling pass.
   ------------------------------------------------------------------
   The course is taught at UIUC and every printed reference it works
   against — Huang, AASHTO, the FAA orders, ASTM — is American. The
   repository therefore spells American, and this script is what makes
   that mechanical rather than a matter of who typed the line.

   It exists mainly because of the two E-Lab ports. gear3d/engine/** is
   a plain copy of upstream and gear3d.js / gear3d.css are generated by
   scripts/port-gear3d/*.mjs; a spelling fixed by hand in any of them is
   lost the next time the port is re-run. Running this last, over the
   copied and generated files alike, is what keeps the fix.

       node scripts/us-english.mjs            # rewrite the repository
       node scripts/us-english.mjs --check    # report, change nothing
       node scripts/us-english.mjs <path>...  # limit to these paths

   Rules are deliberately enumerated rather than derived. A blanket
   -ise -> -ize would eat `noise`, `premise` and `exercise`; a blanket
   -re -> -er would eat nothing here but would the day someone writes
   `centred` inside `concentre`. Every entry below was put there
   because the word is actually in the tree.
   ================================================================== */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/* ---- What is not ours to respell -------------------------------- */

const SKIP_DIRS = new Set([
    '.git', '.astro', '.claude', 'node_modules', 'dist',
    'Chapters', 'Homeworks Fall 2024', 'Contact Stress Predictor'
]);

/* Matched on the path from the repository root, not on the basename.
   `textbook` as a bare name in SKIP_DIRS also matched src/pages/textbook,
   and silently left the whole 20-chapter reading map — the Library
   `catalogue` link included — out of every run. */
const SKIP_PATHS = new Set([
    join('public', 'textbook')       // the PDFs are gitignored and never published
]);

const SKIP_FILES = new Set([
    'package-lock.json',             // npm's tree: @img/colour is a real package
    'package.json',
    join('scripts', 'us-english.mjs'),
    /* The two port transforms quote upstream main.js / styles.css verbatim:
       every `find` argument is an anchor asserted against a file this script
       never sees, and a respelled anchor fails the next sync instead of
       matching it. They are respelled by hand, anchors excepted, and the
       generated gear3d.js / gear3d.css are respelled here as usual — which
       is where the American spelling actually has to land. */
    join('scripts', 'port-gear3d', 'port-main.mjs'),
    join('scripts', 'port-gear3d', 'port-css.mjs')
]);

const SKIP_EXT = /\.(bin|png|jpe?g|gif|webp|avif|ico|woff2?|ttf|otf|eot|pdf|zip|gz|exr|hdr|mp4|webm|npy|pth)$/i;

/* ---- The dictionary ---------------------------------------------
   'stem'  substring, matched in three cases (foo / Foo / FOO), so one
           entry covers every inflection and every camelCase identifier
           built on it: centre -> center also fixes `centreline`,
           `wheelCentres` and `axle-centreline`.
   'word'  the same, but only as a whole word.
   'ise'   the -ise family: the stem is only rewritten when a real
           inflection follows it, so `characteris` cannot eat
           `characteristics` nor `optimis` eat `Optimistic`.
   'exact' literal, case-sensitive, no variants.                     */

const RULES = [
    /* -re / -our / -ue / misc nouns */
    ['stem', 'tyre', 'tire'],
    // before `centre`, or centre+d would land on `centerd`
    ['stem', 'centred', 'centered'],
    ['stem', 'centre', 'center'],
    ['stem', 'metre', 'meter'],
    ['stem', 'fibre', 'fiber'],
    ['stem', 'colour', 'color'],
    ['stem', 'behaviour', 'behavior'],
    ['stem', 'neighbour', 'neighbor'],
    ['stem', 'honour', 'honor'],
    ['stem', 'favour', 'favor'],
    ['stem', 'catalogued', 'cataloged'],
    ['stem', 'catalogue', 'catalog'],
    ['stem', 'analogue', 'analog'],
    ['stem', 'licence', 'license'],
    ['stem', 'artefact', 'artifact'],
    ['stem', 'aluminium', 'aluminum'],
    ['stem', 'judgement', 'judgment'],
    ['stem', 'mould', 'mold'],
    ['word', 'kerb', 'curb'],
    ['word', 'kerbs', 'curbs'],
    ['stem', 'grey', 'gray'],
    ['word', 'ageing', 'aging'],
    ['word', 'maths', 'math'],
    ['word', 'tonne', 'ton'],
    ['word', 'tonnes', 'tons'],
    ['word', 'learnt', 'learned'],

    /* doubled l before a suffix — American singles it, except in
       nouns like `cancellation`, which is why these are inflections
       and not the bare stem */
    ['stem', 'modelled', 'modeled'],
    ['stem', 'modelling', 'modeling'],
    ['stem', 'modeller', 'modeler'],
    ['stem', 'travelled', 'traveled'],
    ['stem', 'travelling', 'traveling'],
    ['stem', 'traveller', 'traveler'],
    ['stem', 'cancelled', 'canceled'],
    ['stem', 'cancelling', 'canceling'],
    ['stem', 'dowelled', 'doweled'],
    ['stem', 'labelling', 'labeling'],
    // `labelled` but never `aria-labelledby`, which is an ARIA name.
    ['exact', /labelled(?!by)/g, 'labeled'],
    ['exact', /Labelled(?!by)/g, 'Labeled'],

    /* -ise / -isation. Stems only where no American word shares them:
       `emphasis`, `synthesis` and `realistic` are all legitimate, so
       those three are spelled out per inflection instead. */
    ['ise', 'idealis', 'idealiz'],
    ['ise', 'rasteris', 'rasteriz'],
    ['ise', 'stabilis', 'stabiliz'],
    ['ise', 'optimis', 'optimiz'],
    ['ise', 'normalis', 'normaliz'],
    ['ise', 'linearis', 'lineariz'],
    ['ise', 'characteris', 'characteriz'],
    ['ise', 'visualis', 'visualiz'],
    ['ise', 'recognis', 'recogniz'],
    ['ise', 'quantis', 'quantiz'],
    ['ise', 'neutralis', 'neutraliz'],
    ['ise', 'generalis', 'generaliz'],
    ['ise', 'digitis', 'digitiz'],
    ['ise', 'summaris', 'summariz'],
    ['ise', 'serialis', 'serializ'],
    ['ise', 'rationalis', 'rationaliz'],
    ['ise', 'penalis', 'penaliz'],
    ['ise', 'oxidis', 'oxidiz'],
    ['ise', 'memoris', 'memoriz'],
    ['ise', 'internalis', 'internaliz'],
    ['ise', 'galvanis', 'galvaniz'],
    ['ise', 'authoris', 'authoriz'],
    ['stem', 'emphasise', 'emphasize'],
    ['stem', 'emphasising', 'emphasizing'],
    ['stem', 'synthesise', 'synthesize'],
    ['stem', 'synthesising', 'synthesizing'],
    ['stem', 'realise', 'realize'],
    ['stem', 'realising', 'realizing'],

    /* -yse. `analyses` is also the American plural of `analysis`, so
       the verb forms are listed and the noun is left alone. */
    ['stem', 'analysed', 'analyzed'],
    ['stem', 'analysing', 'analyzing'],
    ['stem', 'analysable', 'analyzable'],
    ['exact', /Analyse\b/g, 'Analyze'],          // pcaAnalyse and friends
    ['exact', /analyses one gear/g, 'analyzes one gear'],

    /* verb/noun pairs American English collapses */
    ['stem', 'practising', 'practicing'],
    ['stem', 'practise', 'practice']
];

const ISE_SUFFIXES = ['e', 'es', 'ed', 'ing', 'ation', 'ations', 'er', 'ers', 'able', 'ably'];

const cap = (s) => s[0].toUpperCase() + s.slice(1);
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Expand the dictionary into concrete case-sensitive regexes. */
function compile() {
    const out = [];
    for (const [mode, from, to] of RULES) {
        if (mode === 'exact') { out.push([from, to]); continue; }
        const edge = mode === 'word' ? '\\b' : '';
        for (const [f, t] of [
            [from, to],
            [cap(from), cap(to)],
            [from.toUpperCase(), to.toUpperCase()]
        ]) {
            if (mode === 'ise') {
                const suf = f === f.toUpperCase()
                    ? ISE_SUFFIXES.map((x) => x.toUpperCase())
                    : ISE_SUFFIXES;
                out.push([new RegExp(`${esc(f)}(${suf.join('|')})\\b`, 'g'), `${t}$1`]);
                continue;
            }
            out.push([new RegExp(`${edge}${esc(f)}${edge}`, 'g'), t]);
        }
    }
    return out;
}
const COMPILED = compile();

function apply(text) {
    let out = text;
    let hits = 0;
    for (const [re, to] of COMPILED) {
        re.lastIndex = 0;
        const n = (out.match(re) || []).length;
        if (!n) continue;
        hits += n;
        out = out.replace(re, to);
    }
    return { out, hits };
}

/* ---- Walk ------------------------------------------------------- */

function* files(dir) {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, e.name);
        if (e.isDirectory()) {
            if (SKIP_DIRS.has(e.name)) continue;
            if (SKIP_PATHS.has(relative(ROOT, p))) continue;
            yield* files(p);
        } else if (e.isFile()) {
            if (SKIP_EXT.test(e.name)) continue;
            const rel = relative(ROOT, p);
            if (SKIP_FILES.has(e.name) || SKIP_FILES.has(rel)) continue;
            yield p;
        }
    }
}

const args = process.argv.slice(2);
const check = args.includes('--check');
const targets = args.filter((a) => !a.startsWith('--'));
const roots = targets.length ? targets.map((t) => join(ROOT, t)) : [ROOT];

let changed = 0;
let total = 0;
for (const root of roots) {
    const list = statSync(root).isDirectory() ? files(root) : [root];
    for (const p of list) {
        let text;
        try { text = readFileSync(p, 'utf8'); } catch { continue; }
        if (text.includes(' ')) continue;               // binary
        const { out, hits } = apply(text);
        if (!hits) continue;
        changed++;
        total += hits;
        console.log(`${String(hits).padStart(4)}  ${relative(ROOT, p).split(sep).join('/')}`);
        if (!check) writeFileSync(p, out);
    }
}

console.log(check
    ? `\n${total} British spelling(s) in ${changed} file(s).`
    : `\n${total} replacement(s) in ${changed} file(s).`);
if (check && total) process.exitCode = 1;
